
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.numberOfWebAppReplicas }}
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      # template OR include(preferred, can use in pipeline)
      {{- include "webappImage" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort